version: '3'
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
