version: '3'
services:
  app:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=database
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
    volumes:
      - .:/app
      - ~/.gitconfig:/root/.gitconfig
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  database:
